# Em src/main/resources/application.properties

# 1. Porta do Servidor
server.port=8080

# 2. Configuração do Banco de Dados (Azure SQL)
# (Versão corrigida, sem duplicatas ou espaços)

spring.datasource.url=jdbc:sqlserver://srv-helpai-kaique.database.windows.net:1433;databaseName=SistemaChamados;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=kaiqueadmin@srv-helpai-kaique
spring.datasource.password=PIM_unip_2025!

# 3. Configuração do JPA (Tradutor Java-SQL)
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true